name: "update-translators"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 6 * * 0"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-update:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Google Authentication
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: projects/228574713135/locations/global/workloadIdentityPools/github/providers/github-provider
          service_account: db-active-translators@db-active-translators.iam.gserviceaccount.com

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: "Download Artifact: Filtered MJ Database"
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: filter-mj-database.yml
          name: mj-database-filtered
          path: output
          if_no_artifact_found: fail
          use_unzip: true

      - name: Accessing Google Sheets
        run: python3 src/generate_docx.py

      - name: Upload generated .docx
        uses: actions/upload-artifact@v4
        with:
          name: generated-docx
          path: output/active_translators.docx
          retention-days: 7

      - name: Check formatting
        run: black --check .
