name: "update-translators"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-update:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: 3.12
        
      - name: Install dependencies
        run: pip install -r requirements.txt

      # - name: Access Google Sheets
      #   run: python3 src/dummy.py

      - name: Check formatting
        run: black --check .

